### ISSUE TITLE
Unable to save logfiles

### ISSUE THREAD

**Issue by ghost** [flathub/uk.org.greenend.chiark.sgtatham.putty#12]
Hi, i'm unable to save logfiles on putty (when i click on browse in my home folder, no file or directory appears).

**Comment by kowalski7cc** [comment]
This happens because putty flatpak doesn't have access to home and probably it doesn't support usage of portals. You can add access to your home with this command:
```bash
flatpak --user override --filesystem=home uk.org.greenend.chiark.sgtatham.putty
```

You can change `home` with any preferred path, you can learn more at https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access.

You can use also graphical tools to edit application permissions such https://flathub.org/apps/com.github.tchx84.Flatseal

**Comment by ghost** [comment]
OK, it works this way. Thanks a lot for your help !
